spring:
  profiles:
    include: secret

  jpa:
    show-sql: true
    hibernate:
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  datasource:
    # url: ?useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost/DemosecDB